### ISSUE TITLE
Negative Date of Death?

### ISSUE THREAD

**Issue by ajb5d** [AmsterdamUMC/AmsterdamUMCdb#10]
There are a small number of rows where the dateofdeath is negative (suggesting that they died before their first admission?):
`SELECT COUNT(*) FROM admissions WHERE dateofdeath < 0`
`269`

Is this a data error? Am interpreting the field incorrectly?

**Comment by patrickthoral** [comment]
Technically this is a data error, and most likely caused by relative short admissions. The dateofdeath columns is also based on other registries that don't document **time** (just date), so you can imagine that depending on e.g. admission time (in the night) there might be some discrepancies. And indeed, some are really entry errors. It should not be greater than 1 day, though, but I did not verify.
