### ISSUE TITLE
Some variables related to sepsis

### ISSUE THREAD

**Issue by yinchangchang** [AmsterdamUMC/AmsterdamUMCdb#21]
I am working on query some  variables related to sepsis and have found most of them from the code and issue answers, but still not sure about the following:
1. Elixhauser score (premorbid status) and SIRS score
2. IV fluid intake
3. Chloride, BUN, calcium, ionized calcium, carbon dioxide, SGOT, SGPT, PTT, PT, INR, PaCO2

Could you please help me identify them?
Thanks very much!

**Comment by patrickthoral** [comment]
Ad 1) Unfortunately, there is no premorbid status in the database currently. The [SIRS](https://en.wikipedia.org/wiki/Systemic_inflammatory_response_syndrome) score should be easy to calculate using the available vital signs from numericitems
Ad 2) see: fluidin from the [drugitems](https://github.com/AmsterdamUMC/AmsterdamUMCdb/wiki/drugitems) table
Ad 3) Are all numericitems. A lot of them are used in the [severity scores](https://github.com/AmsterdamUMC/AmsterdamUMCdb/tree/master/concepts/severityscores). Please consult your referring intensivist, when struggling to find them, since the Dutch item names are the same or very similar to the English ones. Another helpful resource is [SNOMED CT](https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/SNOMEDCT-NL/2020-09-30&release=&languages=nl,en) for finding synonyms/translations for medical terms.

**Comment by yinchangchang** [comment]
Thanks for your reply.
We want to calculate the IV fluid doses for patients. Should we consider the four following ordercategories or just 2. Spuitpompen in the drugitems table?

ordercategory | ordercategoryid
2. Spuitpompen | 65
Infuus - Bloedproducten | 61
Infuus - Colloid | 17
Infuus - Crystalloid | 55

**Comment by patrickthoral** [comment]
You correctly identified all categories, except for `Voeding Parenteraal` (parenteral nutrition) that is also considered i.v. fluids. 

ordercategoryid | ordercategory
-- | -- 
65 | 2. Spuitpompen
61 | Infuus - Bloedproducten
17 | Infuus - Colloid
55 | Infuus - Crystalloid
15 | Injecties Antimicrobiele middelen
23 | Injecties CZS/Sedatie/Analgetica
24 | Injecties Circulatie/Diuretica
25 | Injecties Haematologisch
67 | Injecties Hormonen/Vitaminen/Mineralen
27 | Injecties Overig
26 | Injecties Tractus Digestivus
39 | Voeding Parenteraal

**Comment by yinchangchang** [comment]
Thanks very much!
