### ISSUE TITLE
Error when admissionid is negative in get_fluidbalance  amsterdamumcdb/fluidbalance.py

### ISSUE THREAD

**Issue by joaocolaco** [AmsterdamUMC/AmsterdamUMCdb#37]
The check .isnumeric() fails when the int is negative, as can sometimes happen with admissionid.

Is more correct to try to convert to the type and check for an error if impossible, replacing:
```
    assert str(admissionid).isnumeric(), "admissionid is not a number: %r" % admissionid
    assert str(from_date).isnumeric(), "from_date is not a number: %r" % from_date
    assert str(to_date).isnumeric(), "to_date is not a number: %r" % to_date
```
with:
```
     try:
      admissionid = np.int64(admissionid)
    except:
      raise Exception("admissionid is not a number: %r" % admissionid)

    try:
      from_date = np.int64(from_date)
    except:
      raise Exception("from_date is not a number: %r" % from_date)

    try:
      to_date = np.int64(to_date)
    except:
      raise Exception("to_date is not a number: %r" % to_date)
```

Best regards.

**Comment by patrickthoral** [comment]
I don't understand why `admissionid` could be a negative value, but you are definitely correct that the code will fail on negative values for `from_date` or `to_date`, though for fluid balance there should not be any data before the first ICU admission. 

However, I did not realize str.isnumeric() required all characters to be numeric to return `True`:

From https://docs.python.org/3/library/stdtypes.html?highlight=isnumeric#str.isnumeric:
> str.**isnumeric()** 
Return True if all characters in the string are numeric characters, and there is at least one character, False otherwise. Numeric  characters include digit characters, and all characters that have the Unicode numeric value property, e.g. U+2155, VULGAR  FRACTION ONE FIFTH. Formally, numeric characters are those with the property value Numeric_Type=Digit, > Numeric_Type=Decimal or Numeric_Type=Numeric.

I will follow your suggestion convert the type and handle the exception.

**Comment by joaocolaco** [comment]
Yes you are right. `admissionid` should not be negative number, I had my wires crossed. I wanted to talk about the dates.

**Comment by patrickthoral** [comment]
Fixed by the latest commit.
