### ISSUE TITLE
ventilator weaning

### ISSUE THREAD

**Issue by shuai720** [AmsterdamUMC/AmsterdamUMCdb#45]
Hi,
I was wondering if there were some indicators of ventilator weaning in this data set, such as the time of weaning, etc. I have searched for the information of ventilation mode in the "listitems" table, but can't find the information about weaning.
Thanks for your help

**Comment by patrickthoral** [comment]
Since there is no such thing as a 'weaning' ventilation mode, it's good to read some background information: https://academic-oup-com.vu-nl.idm.oclc.org/bjaed/article/5/4/113/475175.

In practice that would mean evaluating the moment from a controlled mode -> support mode. And while on support mode, the moment when support is reduced even until '0' or sometimes with T-piece ('kunstneus').
