### ISSUE TITLE
SQL issue in reason_for_admission.ipynb

### ISSUE THREAD

**Issue by tedinburgh** [AmsterdamUMC/AmsterdamUMCdb#49]
I noticed a minor issue with the long SQL query in the notebook for the reasons for admission when rewriting for the code using pandas direct from the data csv files (since my department didn't want me to install postgres). I investigated and it does not seem to affect very many admissions within the cohort, so it's only a small thing!

I'll explain using the diagnoses part of the SQL query as an example, though I think it may affect other parts of the query that are performed in the same way. 

The relevant part of the query is
```
        ROW_NUMBER() OVER(PARTITION BY admissionid
        ORDER BY 
            CASE --prefer NICE > APACHE IV > II > D
                WHEN itemid = 18671 THEN 6 --NICE APACHEIV diagnosen
                WHEN itemid = 18669 THEN 5 --NICE APACHEII diagnosen                
                WHEN itemid BETWEEN 16998 AND 17017 THEN 4 --APACHE IV diagnosis        
                WHEN itemid BETWEEN 18589 AND 18602 THEN 3 --APACHE II diagnosis
                WHEN itemid BETWEEN 13116 AND 13145 THEN 2 --D diagnosis ICU
                WHEN itemid BETWEEN 16642 AND 16673 THEN 1 --DMC diagnosis Medium Care
            END DESC,
            measuredat DESC) AS rownum
```

The problem is that diagnoses are ordered by diagnosis type and time, but when there are multiple entries that share the same diagnosis type and time, then this ordering is not necessarily unique. In this instance, SQL has some internal sorting that will (randomly) sort these entries, and later in the SQL query only the top entry is retained. However, these entries (sharing the same 'key' in the ordering) may correspond to different diagnoses, and may not all be 'surgical' diagnoses (I noticed this because pandas had ordered these entries differently and this lead to different numbers of admissions in each category in the final table). 

I think the solution would to aggregate across entries with the same sorting 'key'. In pandas you might use something like the following code chunk, instead of only taking `WHERE diagnoses.rownum=1` in the SQL query.

```
diagnoses = diagnoses.groupby(['admissionid', 'typeid', 'measuredat']).agg(
        surgical=pd.NamedAgg(column='surgical', aggfunc='any'),
        diagnosis=pd.NamedAgg(column='diagnosis', aggfunc=lambda x: '; '.join(v for v in x.unique())),
        diagnosis_id=pd.NamedAgg(column='diagnosis_id', aggfunc=lambda x: '; '.join(v for v in x.unique()))
    ).reset_index()
```
I'm not experienced in SQL enough to suggest how to modify the query instead.

I hope what I've said here makes sense! As I said, this is only a small issue that affects very few admissions, so I don't know how important it is to rejig the SQL here, but I thought it was worth pointing out.

**Comment by patrickthoral** [comment]
Thanks for pointing this out! Indeed, the intended way was to use the last documented diagnosis, because typically that was a correction on the initial documentation (often by more 'junior' physicians) by staff (intensivists). However, I incorrectly used `measuredat` instead of `updatedat` for sorting. This, as you found out, lead to unpredictable sorting since `measuredat` is not unique for a given admission diagnosis , while `updatedat` should always be unique. I'll fix this shortly.

**Comment by tedinburgh** [comment]
Great, that makes sense! Is it better to use `updatedat' instead of `measuredat' in other situations too?

**Comment by patrickthoral** [comment]
Not necessarily. For most time series the time the measurement belongs to (`measuredat`) is the most relevant one, because that allows us to see the correct order of sequential measurements. The `updatedat` only documents when the record was last updated (or created), which is often slightly later, because nurses, performing most documentation and data validation, will document when they are less busy, but try to make sure that they put the values in the right ‘column’ (i.e. time @ 12:00 hours) of the [flowsheet](https://link.springer.com/article/10.1007/s10877-014-9592-4/figures/1) they are documenting on. However, for measurements/variables that are not really time series (such as the reason for admission) the `measuredat` does not really have a meaning other than the time of the session in which it was created. In those cases the highest `measuredat` (for the same `admissionid`) suggests updates that improved or corrected previous documentation. Especially since APACHE II and IV reasons for admission are used in calculating standardized mortality ratios for national benchmarking, I am quite confident that the most recent value is the ‘correct’ one. Hope this makes the disticntion between the two times more clear.
