### ISSUE TITLE
"Drukzak"-Item in AMDS Database

### ISSUE THREAD

**Issue by aegis301** [AmsterdamUMC/AmsterdamUMCdb#53]
Hi,
my team and I are currently working on machine learning applications in the field of acute kidney injury using the AMDS database. First of all: Thank you so much for providing such high quality data to a scientific public. 

We're currently working up the different features in the database and one item has caught our eye since it shows some importance in different models we're working with: Item No. 8937, called "Drukzak". This is an item measured in ml over a period of time. To us it is not completely clear though what hides behind this item. We translated it to "pressure infusion". But since in some patients only small amounts of volume (100-200ml) are recorded, we were wondering if we were right here. What can we expect a patient received clinically when "Drukzak" is recorded?

Thank you so much in advance for your kind help.

Kindest regards

**Comment by patrickthoral** [comment]
`Drukzak` is the pressure bag from this explanation: https://litfl.com/wp-content/uploads/2019/01/art-line-1.jpg. So basically every patient that has an invasive pressure monitoring system (ABP, CVP, PAP, ICP, etc.) will have one of these bags. The actual volume of infusion is often imprecise because the system used is designed to allow a flow of ~1-5 ml/hour to keep the lines open and the blood/CSF inside the patient.
