### ISSUE TITLE
Mental Health Patients

### ISSUE THREAD

**Issue by MEl3dwi** [AmsterdamUMC/AmsterdamUMCdb#55]
Hello:

I have been trying to find patients with mental diseases from the database, but, could not find any. The only information that I could find relevant to psychiatry is patients who had antipsychotics. This is very weird as Amsterdam University Medical Center has a Department of Psychiatry and the Urban Mental Health Institute.

Could you please confirm this information?

**Comment by patrickthoral** [comment]
Since this is a database for patients admited to an `intensive care unit` (ICU), you should not expect to see many patients that have been admitted primarily for their mental disorder.  The [reason for admission](https://github.com/AmsterdamUMC/AmsterdamUMCdb/blob/master/concepts/diagnosis/reason_for_admission.ipynb) does include patients suffering from drug withdrawal and overdosing, but those are a minority. Many ICU patients do suffer from delirium, but you need to define that yourself (e.g. based on the `Delirium Observation Screening (DOS) scale`, `CAM-ICU` or other criteria) since the database does not have additional diagnoses besides the reason for admission.

In addition, a semi-publicly available dataset with specifics on metal disorders will probably not fullfill de-identification criteria to comply with GDPR.
