### ISSUE TITLE
Identifying patients with a MI diagnosis

### ISSUE THREAD

**Issue by pmugambi** [AmsterdamUMC/AmsterdamUMCdb#80]
I was able to obtain diagnosis information from listitems, but wasn't absolutely sure how to isolate patients with a primary/main diagnosis of AMI. I extracted everyone with a diagnosis containing "myocardial" and cardiogenic shock. 

1) Is this the cohort with MI in the dataset? The sample is quite small so I wanted to be sure it's correct
2) I noted that there are APACHE and APACHE_SEC items as well as NICE and NICE_SEC items. Are there differences in priority for these two? Can I assume each is a valid measure of a "primary/main" diagnosis?

**Comment by patrickthoral** [comment]
Ad 1) Our hospital also has a separate Cardiac Care Unit that is not part of the Department of Intensive Care Medicine so patients without respiratory failure or severe shock won't be admitted to the Intensive Care unit, so indeed you are correct that you would have a small amount of patients.
Ad 2). Yes, the only difference is that sometimes the physician decides to document another (secondary) reason for admission because the reasons for admission were (and still are) used to calculate Standardized Mortality Ratio (SMR) to benchmark ICU's.
