### ISSUE TITLE
Units for certain drug dosages (steroids) missing

### ISSUE THREAD

**Issue by surajraj99** [AmsterdamUMC/AmsterdamUMCdb#84]
Hello,

I was trying to extract the total dosage of steroids patients got during their ICU stay but I noticed that for all the steroids (itemids: 6922,  7106, 10628,  6995,  8132,  9130, 13102, 10582, 13104, 9054, 19133,  9031,  9129), there no units in the preloaded dictionary.

This is how I load in the dictionary:
`import amsterdamumcdb as adb`
`dictionary = adb.get_dictionary()`

When I do this:
`dictionary[dictionary['itemid'].isin(list_of_steroid_item_ids)]`

All of the values under 'unit' are NaN. Is there another place I can get units for the dosage values for these drugs?

**Comment by patrickthoral** [comment]
Since records from `drugitems` don't have a fixed `unit` field per medication, the dictionary does not contain them either. However, for each drug administration you can determine the administered dose using the following fields: 

Name | Type | Description
-- | -- | --
administered | float | administered dose, which may or may not be the same as prescribed dose
administeredunit | string | unit of administered dose (e.g. mg)
administeredunitid | integer | id of administeredunit

See: https://github.com/AmsterdamUMC/AmsterdamUMCdb/wiki/drugitems
